### ISSUE TITLE
TFRecord file size

### ISSUE THREAD

**Issue by Elderpotato** [douglasrizzo/detection_util_scripts#9]
Hi, I have managed to write my TFRecord files using this repo but I realized that the TFRecord is not compressed since it is as big as the file size of the raw images. Is there any way I can further compress it into something smaller?

**Comment by douglasrizzo** [comment]
Hi there. The TFRecord generation script in this repo is very close to the original one, from upstream. It does not employ any kind of compression.

TFRecord compression is possible, see here https://github.com/tensorflow/ecosystem/issues/61. If you're inclined, it seems rather simple to change my `generate_tfrecord.py` script to add the appropriate flags. I believe you can apply what is taught in the link above somewhere in the following line:

https://github.com/douglasrizzo/detection_util_scripts/blob/e4516898644b56e644cf6da51d269736e0028334/generate_tfrecord.py#L131

I just don't know if the TensorFlow Object Detection API accepts compressed TFRecords, since you need to configure the `TFRecordDataset` object (which reads the `.record` file) to read a compressed file instead of an uncompressed one. You'd have to test it.

**Comment by Elderpotato** [comment]
I've tried to insert the following lines of code in to my script but the TFRecord files do not seem to be further compressed.

options = tf.python_io.TFRecordOptions(tf.python_io.TFRecordCompressionType.GZIP)
writer = tf.python_io.TFRecordWriter(outFilePath, options=options)

I'm just curious as to how big are TFRecord files supposed to be as compared to the raw images? Are they normally bigger, smaller or the same? Because right now, I'm trying to make them significantly smaller like using 10 jpg files (35mb) and write a TFRecord that is around 1mb. I'm saying this because I've previously used a 3rd party online software and they managed to achieved compressing it to 1mb.

**Comment by douglasrizzo** [comment]
The main purpose of the TFRecord file format is not to compress a data set, but to save it in a serialized binary format which is very fast for TensorFlow to load and operate on, considerably reducing preprocessing time. It has some other advantages, but none related to compression.

**Comment by douglasrizzo** [comment]
Just to be clear, you should never assume that the TFRecord format will compress your files. Also, you can save other types of data inside TFRecords, not only images, so I don't believe you'll get a comparable compression ratio as the one you got by applying a JPG compression algorithm in your files.

My advice would be for you to first compress your source images and then try serializing them into a TFRecord, or take a look at the input size your neural network works with and scale down your images before serializing them. My script reads the binary contents of the JPG file and saves it in the TFRecord, so, as long as you have smaller files, you should get a smaller TFRecord.

**Comment by Elderpotato** [comment]
Okay thanks for the detailed explanation, I guess I have to look into it further myself.
